### ISSUE TITLE
Overlay fails with "Invalid path"

### ISSUE THREAD

**Issue by chmanchester** [tailhook/libmount#14]
I believe as a result of 8a257067374594414b641dd6092ee4548c2a27f3 I'm having issues with `Overlay::writable` in 0.1.14. nix seems to reject paths it finds containing nulls under some circumstances. If I move from using `CStr` null terminated to `OsStr` in overlay.rs that seems to fix the issue. I'm happy to provide a PR if that sounds like a reasonable solution. Thanks!

**Comment by tailhook** [comment]
This is a bit unexpected. And I'm not sure how switching to OsStr would help (since the actual C function uses C-string anyway). Maybe if you'll show me the code I could understand the issue better.

**Comment by chmanchester** [comment]
Hmm, yes, I'm not confident my approach was correct. The issue is that we have explicit null terminators, and as some point `nix` is rejecting a path due to this check: https://github.com/nix-rust/nix/blob/30b04c59a91d83157d5876b31c7ea6b3b2f44340/src/lib.rs#L255 In particular, the options string seems to hit that: https://github.com/tailhook/libmount/blob/b01684416d5fe0599e62911a3d259b7667f8dd42/src/overlay.rs#L89

**Comment by tailhook** [comment]
Hm, yes, [this](https://github.com/tailhook/libmount/blob/master/src/overlay.rs#L83) line is not needed anymore. I just have to review the whole patch again to figure out what else issues could be, and push a patch.

**Comment by tailhook** [comment]
Fixed this bug and also tmpfs in 0.1.15. Let me know if anything wrong, because it's a bit hard to test.

(also yanked 0.1.14, should have probaly done it earlier)
